source/accounts/urls.py
from django.urls import path
from accounts.views import RegisterView, LoginUserView, Profile

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('profile/', Profile.as_view(), name='profile'),
]

source/applicant/urls.py
from django.urls import path
from applicant.views import ProfileApplicantView, ProfileDeleteView, CustomPasswordChangeView, ResumeCreationView, ResumesView, ResumeDetailView, IndexApplicantView, EmployerDetailView, JobDetailView, ResponsesView, ResponseApplicantDetailView


urlpatterns = [
    path('', IndexApplicantView.as_view(), name='index_applicant'),
    path('profile/<int:pk>', ProfileApplicantView.as_view(), name='profile_applicant'),
    path('profile/<int:pk>/del', ProfileDeleteView.as_view(), name='profile_del'),
    path('password-change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('resume_add/', ResumeCreationView.as_view(), name='resume_add'),
    path('resumes/', ResumesView.as_view(), name='resumes'),
    path('resume_detail/<int:pk>', ResumeDetailView.as_view(), name='resume_detail'),
    path('employer_detail/<int:pk>', EmployerDetailView.as_view(), name='employer_detail'),
    path('job_detail/<int:pk>', JobDetailView.as_view(), name='job_detail_response'),
    path('responses/', ResponsesView.as_view(), name='responses_applicant'),
    path('response_detail/<int:pk>', ResponseApplicantDetailView.as_view(), name='response_detail_applicant')
]

source/webproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import logout_view, is_autorization

urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout/', logout_view, name='logout'),
    path("auth/", include('accounts.urls')),
    path("applicant/", include('applicant.urls')),
    path('employer/', include('employer.urls')),
    path('', is_autorization, name='is_autorization')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/applicant/models.py
from django.db import models
from django.contrib.auth import get_user_model



class CategoryJob(models.Model):
    title = models.CharField(verbose_name='Категория вакансии', max_length=50, blank=False, null=False)

    def __str__(self):
        return self.title



class Resume(models.Model):
    title = models.CharField(
        verbose_name='Название(должность)',
        max_length=50,
        null=False,
        blank=False
    )
    category = models.ForeignKey(
        verbose_name='Катeгория вакансии',
        to='applicant.CategoryJob',
        on_delete=models.CASCADE,
        null=False,
        blank=False
    )
    salary = models.IntegerField(
        verbose_name='Ожидаемая заработная плата',
        null=True,
        blank=True
    )
    author = models.ForeignKey(
        verbose_name='Автор резюме',
        to=get_user_model(),
        related_name='resumes',
        on_delete=models.CASCADE,
        null=False,
        blank=False
    )
    is_published = models.BooleanField(
        verbose_name='Опубликовать',
        null=True,
        blank=True,
        default=True
    )
    created_at = models.DateTimeField(
        verbose_name='Дата создания',
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name='Дата обновления',
        auto_now=True
    )

    def __str__(self):
        return self.title



class WorkExperience(models.Model):
    begin_date = models.DateField(
        verbose_name='Начало работы',
        null=False,
        blank=False
    )
    end_date = models.DateField(
        verbose_name='Окончание',
        null=False,
        blank=False
    )
    position = models.CharField(
        verbose_name='Должность',
        max_length=50,
        null=False,
        blank=False
    )
    organization = models.CharField(
        verbose_name='Организация',
        max_length=50,
        null=False,
        blank=False
    )
    responsibility = models.TextField(
        verbose_name='Обязанности',
        max_length=2000,
        null=False,
        blank=False
    )
    resume = models.ForeignKey(
        verbose_name='Резюме',
        to='applicant.Resume',
        related_name='work_experiences',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.organization



class Education(models.Model):
    title = models.CharField(
        verbose_name='Название учебного заведения',
        max_length=50,
        null=False,
        blank=False
    )
    faculty = models.CharField(
        verbose_name='Факультет',
        max_length=50,
        null=False,
        blank=False
    )
    speciality = models.CharField(
        verbose_name='Специальность',
        max_length=50,
        null=False,
        blank=False
    )
    end_date_education = models.DateField(
        verbose_name='Дата окончания',
        null=False,
        blank=False
    )
    resume = models.ForeignKey(
        verbose_name='Резюме',
        to='applicant.Resume',
        related_name='educations',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title



class Response(models.Model):
    job = models.ForeignKey(
        verbose_name='Вакансия',
        to='employer.Job',
        related_name='responses',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        verbose_name='Соискатель',
        to='accounts.Account',
        related_name='responses',
        on_delete=models.CASCADE
    )
    resume = models.ForeignKey(
        verbose_name='Резюме соискателя',
        to='applicant.Resume',
        related_name='responses',
        on_delete=models.CASCADE
    )


class Chat(models.Model):
    response = models.ForeignKey(
        verbose_name='Отклик',
        to='applicant.Response',
        related_name='chats',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        verbose_name='Пользователь',
        to='accounts.Account',
        related_name='chats',
        on_delete=models.CASCADE
    )
    text = models.TextField(
        verbose_name='Текст сообщения',
        max_length=2000,
        null=False,
        blank=False
    )

source/applicant/forms.py
from django import forms
from applicant.models import Resume, WorkExperience, Education, Chat, Response
from django.forms import modelformset_factory

work_experience_formset = modelformset_factory(
    WorkExperience, 
    fields=('begin_date', 'end_date', 'position', 'organization', 'responsibility'),
    extra=1
)

education_formset = modelformset_factory(
    Education, 
    fields=('title', 'faculty', 'speciality', 'end_date_education'),
    extra=1
)

class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ('title', 'category', 'salary', 'is_published')


class WorkForm(forms.ModelForm):
    class Meta:
        model = WorkExperience
        fields = ('begin_date', 'end_date', 'position', 'organization', 'responsibility')


class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ('text',)

class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = '__all__'

source/applicant/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, View, DeleteView, UpdateView, CreateView, ListView, TemplateView
from django.contrib.auth import get_user_model
from django.contrib.auth.views import PasswordChangeView
from applicant.models import Resume, WorkExperience, Education, Response, Chat
from applicant.forms import work_experience_formset, ResumeForm, education_formset, ChatForm, ResponseForm
from accounts.models import Account
from employer.models import Job



class ProfileApplicantView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'applicant/profile.html'
    context_object_name = 'user_obj'
    fields =['username', 'first_name', 'phone', 'email', 'telegram', 'facebook', 'linkedin', 'avatar']

    def get_success_url(self):
        return reverse('profile_applicant', kwargs={'pk': self.request.user.id})



class ProfileDeleteView(LoginRequiredMixin, DeleteView):
    model = get_user_model()
    success_url = reverse_lazy('login')


class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy("login")
    template_name = "applicant/password_change_form.html"


class ResumeCreationView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        form_resume = ResumeForm
        form_work = work_experience_formset(queryset=WorkExperience.objects.none())
        form_education = education_formset(queryset=Education.objects.none())
        return render(self.request, 'applicant/resume_add.html', {'form_resume': form_resume, 'form_work': form_work, 'form_education': form_education})

    def post(self, *args, **kwargs):
        form_resume = ResumeForm(self.request.POST)
        form_work = work_experience_formset(data=self.request.POST, queryset=WorkExperience.objects.none())
        form_education = education_formset(data=self.request.POST, queryset=Education.objects.none())
        if all([form_resume.is_valid(), form_work.is_valid(), form_education.is_valid()]):
            resume = form_resume.save(commit=False)
            author = get_object_or_404(Account, pk=self.request.user.id)
            resume.author = author
            resume.save()
            for form in form_work.cleaned_data:
                if form:
                    begin_date = form['begin_date']
                    end_date = form['end_date']
                    position = form['position']
                    organization = form['organization']
                    responsibility = form['responsibility']
                    resume_id = resume
                    work = WorkExperience.objects.create(begin_date=begin_date, end_date=end_date, position=position, organization=organization, responsibility=responsibility, resume=resume_id)
                    work.save()
            for form in form_education.cleaned_data:   
                if form:
                    title = form['title']
                    faculty = form['faculty']
                    speciality = form['speciality']
                    end_date_education = form['end_date_education']
                    resume_id = resume
                    education = Education.objects.create(title=title, faculty=faculty, speciality=speciality, end_date_education=end_date_education, resume=resume_id)
                    education.save()
            return redirect('index_applicant')
        else:
            form_resume = ResumeForm(self.request.POST)
            form_work = work_experience_formset(self.request.POST)
            form_education = education_formset(self.request.POST)
            return render(self.request, 'applicant/resume_add.html', {'form_resume': form_resume, 'form_work': form_work, 'form_education': form_education})



class ResumesView(LoginRequiredMixin, ListView):
    template_name = 'applicant/resumes.html'
    model = Resume
    context_object_name = 'resumes'

    def get_queryset(self):
        return Resume.objects.filter(author=self.request.user, is_published=True)



class ResumeDetailView(LoginRequiredMixin, DetailView):
    template_view = 'applicant/resume_detail.html'
    model = Resume


class IndexApplicantView(LoginRequiredMixin, ListView):
    template_name = 'applicant/index.html'
    model = Job
    context_object_name = 'jobs'

    def get_queryset(self):
        return Job.objects.filter(is_deleted=True).order_by('-updated_at')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        if Resume.objects.filter(author=self.request.user.pk).exists():
            context['is_resume'] = True
        else:
            context['is_resume'] = False
        return context


class EmployerDetailView(LoginRequiredMixin, DetailView):
    template_name = 'applicant/employer_detail.html'
    model = get_user_model()
    context_object_name = 'user_obj'


class JobDetailView(LoginRequiredMixin, DetailView):
    template_name = 'applicant/job_detail.html'
    model = Job
    context_object_name = 'job'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        resumes = Resume.objects.filter(author=self.request.user.pk)
        chat_form = ChatForm
        context['resumes'] = resumes
        context['chat'] = chat_form
        return context

    def post(self, *args, **kwargs):
        print(self.request.POST)
        resume = get_object_or_404(Resume, pk=self.request.POST.get('resume'))
        job = get_object_or_404(Job, pk=kwargs['pk'])
        author = get_object_or_404(Account, pk=self.request.user.id)
        text_form = ChatForm(self.request.POST)
        if text_form.is_valid():
            response = Response.objects.create(author=author, job=job, resume=resume)
            response.save()
            text = text_form.save(commit=False)
            text.author = author
            text.response = Response.objects.last()
            text.save()
            return redirect('index_applicant')
        else:
            return redirect('job_detal', pk=kwargs['pk'])


class ResponsesView(LoginRequiredMixin, ListView):
    template_name = 'applicant/responses.html'
    context_object_name = 'responses'
    model = Account

    def get_queryset(self):
        return Account.objects.get(pk=self.request.user.pk)


class ResponseApplicantDetailView(LoginRequiredMixin, DetailView):
    template_name = 'applicant/response_detail.html'
    model = Response
    context_object_name = 'response'
    

source/applicant/templates/applicant/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{{ title }}{% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link type="text/css"  href="{% static 'applicant/css/style.css' %}" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'index_applicant' %}">
            <img class="logo-hh" src="{% static 'accounts/img/logo-hh.png' %}" alt="logo">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'resumes' %}">Мои резюме</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'responses_applicant' %}">Отклики</a>
              </li>
            </ul>
            <span class="navbar-text">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item pt-1">
                      <a class="nav-link" href="{% url 'resume_add' %}">Создать резюме</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'profile_applicant' user.pk %}">
                          <img src="{% static 'applicant/img/profile.png' %}" alt="">
                      </a>
                    </li>
                </ul>
            </span>
          </div>
        </div>
    </nav>           
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

source/applicant/templates/applicant/employer_detail.html
{% extends 'applicant/base.html' %}

{% load static %}

{% block content %}
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 block">
    <div class="text-center my-5">
        {% if user_obj.avatar %}
        <p><img class="avatar" src="{{ user_obj.avatar.url }}" alt="photo"></p>
        {% else %}
        <p><img class="avatar" src="{% static 'applicant/img/no-photo.png' %}" alt="photo"></p>
        {% endif %}
        <p><strong>{{ user_obj.username }}</strong></p>
    </div>
    <div class="text-left my-5">
        <p><strong class="me-3">Название организации:</strong>{{ user_obj.first_name }}</p>
        <p><strong class="me-3">Номер телефона:</strong>{{ user_obj.phone }}</p>
        <p><strong class="me-3">Адрес электронной почты:</strong>{{ user_obj.email }}</p>
        <p><strong class="me-3">Telegram:</strong>{{ user_obj.telegram }}</p>
        {% if user_obj.telegram %}
        <p><strong class="me-3">Facebook:</strong>{{ user_obj.facebook }}</p>
        {% endif %}
        {% if user_obj.telegram %}
        <p><strong class="me-3">Linkedin:</strong>{{ user_obj.linkedin }}</p>
        {% endif %}
    </div>
</div>

<script src="{% static 'applicant/js/profile_update.js' %}"></script>
{% endblock %}

source/applicant/templates/applicant/index.html
{% extends 'applicant/base.html' %}

{% load static %}

{% block content %}
<div class="row block">
    <div class="col-lg-12 mx-auto mb-5">
        {% if is_resume %}
        <h2 class="text-start my-5 ms-5">Все вакансии</h2>
            {% for job in jobs %}
            <div class="card text-center mb-3">
                <div class="card-body">        
                    <div class="row row-cols-1 row-cols-md-5 row-cols-lg-5 block">
                        <div><h5 class="card-title text-start ms-2">{{ job.title }}</h5></div>
                        <div><p class="card-text">Дата обновления: {{ job.updated_at }}</p></div>
                        <div><p>З/П: {{ job.salary }}</p></div>
                        <div><p><a href="{% url 'employer_detail' job.author.pk %}">{{ job.author }}<a></a></p></div>
                        <div><p><a href="{% url 'job_detail_response' job.pk %}" class="btn btn-primary">Подробнее</a></p></div>
                    </div> 
                </div>
                </a>
            </div>
            {% endfor %}
        {% else %}
        <h2 class="text-start my-5">Вы не можете проссматривать вакансии, пока не создадите резюме</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

source/applicant/templates/applicant/job_detail.html
{% extends 'applicant/base.html' %}
{% block title %}
{% endblock %}


{% block content %}
<div class="block">
    <h2 class="text-center pt-5">Вакансия "{{ job.title }}"</h2>
    <div class="row mt-5 pb-5">
        <div class="col-lg-10 mx-auto">   
                <div class="text-start ps-5">          
                    <p><strong>Заработная плата: </strong>{{ job.salary }}</p> 
                    <p><strong>Требуемый опыт работы:</strong> {{ job.experiences }}</p>
                    <p><strong>Описание:</strong></p>
                    <p>{{ job.description|linebreaks }}</p>
                    <p>
                        <button type="button" class="btn btn-success btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Откликнуться
                        </button>
                    </p>
                </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Отклик на вакансию "{{ job.title }}"</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            <form action="" method="POST">
                {% csrf_token %}
                <p>Выберете резюме которое вы хотите прикрепить:</p>
                <select name="resume" id="" class="form-select">
                    {% for resume in resumes %}
                        <option value="{{ resume.pk }}">{{ resume.title }}</option>
                    {% endfor %}
                </select>
                <p class="pt-4">Сообщение работадателю:</p>
                {{ chat.text }}
            </div>
            <div class="modal-footer">
                    <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Отправить</button>
                    <a href="" type="button" class="btn btn-primary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $('#id_text').addClass('form-control')
</script>
{% endblock %}

source/applicant/templates/applicant/password_change_form.html
{% extends 'applicant/base.html' %}

{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-5 mx-auto">
            <div class="border rounded-1 rounded-bottom mt-5 block">
                <h4 class="text-center border-bottom p-3 bg-dark bg-gradient text-white">
                    Смена пароля
                </h4>
                <div class="row">
                    <div class="form-error text-danger fw-light">{{ form.non_field_errors }}</div>
                    <div class="col-lg-8 mx-auto mt-4">
                        <form class="text-center" method="POST">
                            {% csrf_token %}   
                            <div class="input-group">
                                {% for f in form %}
                                <p class="text-start mb-2 mx-2 fw-light"><strong>{{ f.label }}</strong></p>
                                <p class="text-start w-100 mx-2"> {{ f }}</p>
                                <div class="form-error text-danger">{{ f.errors }}</div>
                                {% endfor %}
                            </div>
                            <p class="text-center mt-2 mb-5"><input class="btn btn-primary bg-gradient rounded-1 px-4" type="submit" value="Сменить пароль"></p>         
                        </form>
                    </div>
                </div>
            </div> 
        </div>
    </div>
    <script src="{% static 'applicant/js/password_change.js' %}"></script>
{% endblock %}

source/applicant/templates/applicant/response_detail.html
{% extends 'applicant/base.html' %}
{% block title %}
{% endblock %}


{% block content %}
<div class="block">
    <h2 class="text-center pt-5">Отклик на вакансию "{{ response.job.title }}"</h2>
    <div class="row mt-5 pb-5">
        <div class="col-lg-8 mx-auto">   
                <div class="text-start ps-5">          
                    <p><strong>Заработная плата: </strong>{{ response.job.salary }}</p> 
                    <p><strong>Требуемый опыт работы:</strong> {{ response.job.experiences }}</p>
                    <p><strong>Описание:</strong></p>
                    <p>{{ response.job.description|linebreaks }}</p>
                    <p><h5>Чат с работодателем:</h5></p>
                    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 block">
                        {% for chat in response.chats.all %}
                        <div>
                            <p><strong>{{ chat.author }}</strong></p>
                        </div>
                        <div>
                            <p>{{ chat.text }}</p>
                        </div>
                        {% endfor %}
                    </div>
                    
                </div>
        </div>
    </div>
</div>
{% endblock %}

source/applicant/templates/applicant/resume_add.html
{% extends 'applicant/base.html' %}

{% load static %}

{% block title %}Создать резюме{% endblock %}

{% block content %}
<div class="container">
    <div class="row block">
        <div class="col-lg-9 mx-auto mt-4">
            <h2 class="text-start ms-2 my-5">Основная информация</h2>
            <form id="form-container" class="text-center" action="" method="POST">
                {% csrf_token %} 
                <div class="form-error text-center text-danger fw-light">{{ form_resume.non_field_errors }}</div>
                <div class="input-group">
                    {% for f in form_resume %}
                    <p class="text-start mb-2 mx-2 fw-light"><strong>{{ f.label }}</strong></p>
                    <p class="text-start w-100 mx-2"> {{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                </div>
                <h2 class="text-start ms-2 my-5">Опыт работы</h2>
                <p class="text-start ms-2 mt-2 mb-2"><input id="btn-show-work" class="btn btn-secondary bg-gradient rounded-1 px-4" type="button" value="Показать опыт работы"></p>
                {{form_work.management_form}}
                <div id="work-form" class="input-group work-form mb-5">
                    {% for form in form_work %}
                    <div class="work">
                        {{form.as_p}}
                    </div>
                    {% endfor %} 
                </div>
                <button class="btn btn-secondary bg-gradient rounded-1 px-4" id="add-form" type="button">Добавить место работы</button>
                <input id="btn-hidden-work" class="ms-2 btn btn-danger bg-gradient rounded-1 px-4" type="button" value="Убрать опыт работы">
                <h2 class="text-start ms-2 my-5">Образование</h2>
                <div id="work-form-education" class="input-group mb-5">
                    {% for form in form_education %}
                    <div class="education w-100">
                        {{form.as_p}}
                    </div>
                    {% endfor %} 
                </div>  
                <button class="btn btn-secondary bg-gradient rounded-1 px-4" id="add-form-education" type="button">Добавить образование</button>    
                <p class="text-center mt-2 mb-5"><input class="btn btn-primary bg-gradient rounded-1 px-4" type="submit" value="Сохранить"></p>
            </form>
        </div>
    </div>
</div>
<script>
    $('#id_is_published').addClass('form-control');
    $('#id_title').addClass('form-control');
    document.getElementById('btn-show-work').hidden = true;
    document.getElementById('btn-show-work').onclick = function() {
        document.getElementById('work-form').hidden = false;
        document.getElementById('btn-hidden-work').hidden = false;
        document.getElementById('btn-show-work').hidden = true;
        document.getElementById('add-form').hidden = false;
    }
    document.getElementById('btn-hidden-work').onclick = function() {
        document.getElementById('work-form').hidden = true;
        document.getElementById('btn-show-work').hidden = false;
        document.getElementById('btn-hidden-work').hidden = true;
        document.getElementById('add-form').hidden = true;
    }
    $('.work input')[0].className = 'text-start w-100 form-control'
    $('.work p')[0].className = 'text-start mb-2 mx-2 fw-light'
    $('.work input')[0].attributes[0].nodeValue = 'date'
    $('.work input')[1].className = 'text-start w-100 form-control'
    $('.work p')[1].className = 'text-start mb-2 mx-2 fw-light'
    $('.work input')[1].attributes[0].nodeValue = 'date'
    $('.work input')[2].className = 'text-start w-100 form-control'
    $('.work p')[2].className = 'text-start mb-2 mx-2 fw-light'
    $('.work input')[3].className = 'text-start w-100 form-control'
    $('.work p')[3].className = 'text-start mb-2 mx-2 fw-light'
    $('.work p')[4].className = 'text-start mb-2 mx-2 fw-light'
    $('.work textarea').addClass('form-control')
    $('.work textarea')[0].attributes[1].value = 60
    $('.work textarea')[0].attributes[2].value = 5

    $('.education input')[0].className = 'text-start w-100 form-control'
    $('.education p')[0].className = 'text-start mb-2 mx-2 fw-light'
    $('.education input')[1].className = 'text-start w-100 form-control'
    $('.education p')[1].className = 'text-start mb-2 mx-2 fw-light'
    $('.education input')[2].className = 'text-start w-100 form-control'
    $('.education p')[2].className = 'text-start mb-2 mx-2 fw-light'
    $('.education input')[3].className = 'text-start w-100 form-control'
    $('.education p')[3].className = 'text-start mb-2 mx-2 fw-light'
    $('.education input')[3].attributes[0].nodeValue = 'date'
    console.log($('.work textarea')[0].attributes[2].value)

    let workForm = document.querySelectorAll("#work-form")
    let container = document.querySelector("#form-container")
    let addButton = document.querySelector("#add-form")
    let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
    let formNum = workForm.length-1

    addButton.addEventListener('click', addForm)
    function addForm(e){
        e.preventDefault()

        let newForm = workForm[0].cloneNode(true)
        let formRegex = RegExp(`form-(\\d){1}-`,'g')

        formNum++
        newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
        container.insertBefore(newForm, addButton)
            
        totalForms.setAttribute('value', `${formNum+1}`)
        console.log(formNum)
    }
    let educationForm = document.querySelectorAll("#work-form-education")
    let addButtonEducation = document.querySelector("#add-form-education")
    let totalFormsEducation = document.querySelector("#id_form-TOTAL_FORMS")
    let formNumEducation = educationForm.length
    console.log(educationForm)
    addButtonEducation.addEventListener('click', addFormEducation)
    function addFormEducation(e){
        e.preventDefault()

        let newForm = educationForm[0].cloneNode(true)
        let formRegex = RegExp(`form-(\\d){1}-`,'g')

        formNumEducation++
        newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNumEducation}-`)
        container.insertBefore(newForm, addButtonEducation)
            
        totalFormsEducation.setAttribute('value', `${formNumEducation+1}`)
        
    }
</script>
<script src="{% static 'applicant/js/resume_add.js' %}"></script> 
{% endblock %}